server {
    listen 8080;
    listen [::]:8080;
    server_name _;

    root /workspace;
    index index.html;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    location / {
        add_header Cache-Control "no-store";
        try_files $uri $uri/ =404;
    }
}
